### ISSUE TITLE
The icon has disappeared from the toolbar and the Safari extensions tab

### ISSUE THREAD

**Issue by orjlin** [jlnbxn/markdownloader#1]
Tried reinstalling, but Markdownloader Version 3.1.0 (3) still has the same behaviour:

- not visible on the toolbar
- when starting manually and hitting "Quit and open Safari extensions preferences" - nothing happens

Using 
- Safari Version 15.3 (17612.4.9.1.8)
- MacOS 12.2.1 (21D62)
  
On an intel iMac 2017

**Comment by jlnbxn** [comment]
Been a long time, but still: You are referring to the [MarkDownload](https://github.com/deathau/markdownload) extension instead of the _Markdownloader_ website, which this is the repository of.
